---
# Playbook to install the DB and create a DB user

- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - MySQL-python


- name: Configuer SELinux for mysql
  seboolean: name=mysql_connect_any state=true persistent=yes


- name: MySQL configuration
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb


- name: Create DB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775


- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775


- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes


- name: Start firewalld
  service: name=firewalld state=started enabled=yes


- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes


- name: Create Application Database
  mysql_db: name={{ dbname }} state=present


- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
