---
# Playbook for plays to be run on all hosts

- name: Update all packages
  yum: 
    name: '*'
    state: latest

- name: Install ntp
  yum: 
    name: ntp 
    state: present
  tags: ntp

- name: Install firewalld and SELinux tools
  yum: name={{ item }} state=installed 
  with_items:
   - libselinux-python
   - libsemanage-python
   - firewalld

- name: Configure ntp 
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start and enable ntp
  service: name=ntpd state=started enabled=yes
  tags: ntp
